### ISSUE TITLE
Не работает настройка карт по онлайну

### ISSUE THREAD

**Issue by UnrealKaraulov** [Mistrick/MapManagerModular#28]
Кто-то писал что все работает, но что-то на это не похоже.

de_dust2_2x2 0 16 1
de_inferno_2x2 0 16 1
awp_india2 0 16 1
$2000$ 0 16 1
aim_deagle5 0 16 1
aim_headshot 0 16 1
dm_library_b01 0 16 1
cs_16fighter 0 16 1

К примеру вот эти карты должны исчезать из списка (ЧТО БЫ ИХ НЕЛЬЗЯ БЫЛО НОМИНИРОВАТЬ) если игроков БОЛЬШЕ 16 если все верно настроено.

Но почему-то этого не происходит и все игроки без проблем могут номинировать карты не предназначенные для этого онлайна.

включено mapm_sort_check_nominated_maps "1", толку никакого, карты все равно в списке.

**Comment by UnrealKaraulov** [comment]
@Mistrick 
Когда я сделал патч исправляющий эту ошибку ты написал что у тебя и так все работает, объясни популярно как именно

**Comment by Mistrick** [comment]
Конфиг пробовал читать?

**Comment by UnrealKaraulov** [comment]
Так ты не пиши тогда что твой гoвноплагин нормально работает, ну раз даёшь разрешение я так и сделаю везде опубликую как исправленную версию твоего гoвноплагина. Раз ты сам не можешь сделать эту фундаментальную функцию. Нахрена настройки онлайна если они не работают и игроки могут выбирать маленькие карты ($2000$ при 32 игроках).

**Comment by UnrealKaraulov** [comment]
Они даже не в низу списка, а в случайных местах
