### ISSUE TITLE
Рандомный список карт

### ISSUE THREAD

**Issue by UnrealKaraulov** [Mistrick/MapManagerModular#29]
Игроки смотрят на название карт а не на цифры, хотелось бы что бы функция делала рандомный список карт, а не меняла кнопки местами ) @Mistrick у тебя сделано как-то по eвpeйcки

Игрок смотрит первая в списка dust2 , жмет 1, а оказывается нажимает какую-то рандомную карту или продление.

Если игрок много лет играет он уже не обращает внимание на цифры и получается что игроки выбирают карту на которой никто не хочет играть.

**Comment by Mistrick** [comment]
>хотелось бы что бы функция делала рандомный список карт, а не меняла кнопки местами

Что такое рандомный список карт? В голосовании всегда рандомный список.
Если вам не нравится функция квара, зачем вы ее используете?
>Если игрок много лет играет он уже не обращает внимание на цифры и получается что игроки выбирают карту на которой никто не хочет играть.

Вы точно играли подряд несколько раз с включенным `mapm_random_nums`? Квар задумывался специально, чтобы люди не выбирали одни и те же карты. Ошибка по невнимательности одна из причин выбрать новую карту. Но проблема в другом. Игроки не такие, как вы описываете. Фокус работает 2-4 карты, после включения квара. После этого почти никто не голосует случайно.

**Comment by Mistrick** [comment]
Что вам сказать, ищите плагин без еврейский функций.
