### ISSUE TITLE
Old map name in chat if a new name is set via `mapm_set_displayed_name`

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Mistrick/MapManagerModular#34]
In chat during voting the results shows old map name, although a new map name is set via `mapm_set_displayed_name`

**Comment by Mistrick** [comment]
This native for displayed name in menu. Mainly for additional info about map.
In chat should be original map name.

**Comment by Nord1cWarr1or** [comment]
> This native for displayed name in menu. Mainly for additional info about map. In chat should be original map name.

got it
