### ISSUE TITLE
Не хватает colorchat.inc

### ISSUE THREAD

**Issue by BaHeK1994** [Mistrick/MapManagerModular#6]
https://github.com/Mistrick/MapManagerModular/blob/master/addons/amxmodx/scripting/map_manager_core.sma#L6

При компиляции на amxmodx 1.8.2 инклюдится colorchat, но его нет в папке includes и нет readme, какой именно нужно использовать.

**Comment by Mistrick** [comment]
You can use inc from old version of map manager.

**Comment by Mistrick** [comment]
Drop AMXX 1.8.2 support with new releases.
